### ISSUE TITLE
MAXBEST expected on Game

### ISSUE THREAD

**Issue by ahensel** [stevens68/twixtbot-ui#113]
I just recently installed twixtbot_ui. I'm using Python 3.10.

It seems I need to add a line to `src/backend/twixt.py` to get MCTS to work:
```py
 class Game:
+    MAXBEST = 24**24
     SIZE = 24
```

As the code currently stands, any attempt to use MCTS results in the following error:
```
Exception in thread Thread-2 (call_bot):
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/alphazero/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/alphazero/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/alan/projects/twixtbot-ui/src/tbui.py", line 399, in call_bot
    response = self.bots[self.game.turn].pick_move(
  File "/Users/alan/projects/twixtbot-ui/src/backend/nnmplayer.py", line 128, in pick_move
    N = self.nm.mcts(game, self.num_trials, window, event)
  File "/Users/alan/projects/twixtbot-ui/src/backend/nnmcts.py", line 325, in mcts
    resp = self.create_response(
  File "/Users/alan/projects/twixtbot-ui/src/backend/nnmcts.py", line 278, in create_response
    indices = numpy.argsort(self.root.N)[::-1][:game.MAXBEST]
AttributeError: 'Game' object has no attribute 'MAXBEST'
```

Of course, I am not confident in my solution. I don't know what `MAXBEST` is. I copied the value from a few lines higher in the code, outside of the `Game` class.

**Comment by stevens68** [comment]
Fixed in release 26.2
